version: "3"
services:
  carapp-api:
    build: .
    depends_on:
      - "carapp-db"
    links:
      - carapp-db
    ports:
      - "8083:8080"
  carapp-db:
    image: mysql:latest
    container_name: carapp-db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=carapp_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USER=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
      - TZ=Europe/Rome
