version: "3"
services:
  ecommerce-app:
    build: .
    depends_on:
      - "ecommerce-db"
    links:
      - ecommerce-db
    ports:
      - "8080:8080"
  ecommerce-db:
    image: mysql:latest
    container_name: ecommerce-db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USER=root
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
      - TZ=Europe/Rome
